### ISSUE TITLE
Failure to deploy on AL2022(aarch64)

### ISSUE THREAD

**Issue by allywilson** [ubergeek77/Lemmy-Easy-Deploy#1]
Deployed on Amazon Linux 2022 (aarch64) (It's a Fedora clone if you've not used it). Get a blank page after deployment.

Docker logs for the lemmy container:

> exec /app/lemmy: exec format error
> exec /app/lemmy: exec format error
> exec /app/lemmy: exec format error
> exec /app/lemmy: exec format error
> exec /app/lemmy: exec format error
> exec /app/lemmy: exec format error
> exec /app/lemmy: exec format error
> exec /app/lemmy: exec format error
> exec /app/lemmy: exec format error
> exec /app/lemmy: exec format error
> exec /app/lemmy: exec format error
> exec /app/lemmy: exec format error
> exec /app/lemmy: exec format error
> exec /app/lemmy: exec format error
> exec /app/lemmy: exec format error
> exec /app/lemmy: exec format error
> exec /app/lemmy: exec format error

deploy.sh completes successfully:

> Setup complete! Lemmy version 0.17.4 deployed!

Any ideas?

Much appreciate any help!

**Comment by ubergeek77** [comment]
Ah, sorry about this. I assumed Lemmy was pushing ARM images to Docker Hub, but it looks like they are not. They do have a separately tagged image for 0.17.3, but it looks like they don't consistently keep them up to date, since there's no ARM image for 0.17.4.

It also looks like I need some better health checks for that "success" message. It's nothing more than an `echo`, and I naively don't check the actual status of the deployment :p

You can still use my deployment script, but since you're on ARM, and Lemmy does not provide an ARM image, you'll have to compile Lemmy from source. This will greatly increase deploy time (builds can take 30+ minutes), but here is how you can do that:

- Set `BUILD_FROM_SOURCE` to `true` in `config.env`
- Run `./deploy.sh -f`

In the future, I'll add a check that does this for you if the Docker Hub image doesn't support your arch, but for now, this should get you up and running.

Please let me know if this works!

**Comment by ubergeek77** [comment]
I've added a somewhat graceful fallback for this type of issue. Please pull the latest version of Lemmy-Easy-Deploy and try your deployment again.

If Lemmy-Easy-Deploy detects you're not running an x86_64 system, it will override the config option in `config.env` and automatically build from source.

Until Lemmy manages their multiarch images on Docker Hub a bit better, this is the best I can do for the time being.

Let me know if this gets you up and running!
