### ISSUE TITLE
can't build rc tag?

### ISSUE THREAD

**Issue by lordkitsuna** [ubergeek77/Lemmy-Easy-Deploy#10]
I've enabled build from source in config and I'm attempting to get my server to update to https://github.com/LemmyNet/lemmy/releases/tag/0.18.0-rc.6 but both with and without manual it can't seem to find this version.

**Comment by ubergeek77** [comment]
It would help if you followed the issue template :)

**Comment by lordkitsuna** [comment]
```
==== Docker Information ====
Detected runtime: docker (Docker version 24.0.2, build cb74dfcd85)
Detected compose: docker compose (Docker Compose version 2.19.0)
   Runtime state: OK

==== System Information ====
MEMORY:                total        used        free      shared  buff/cache   available
Mem:           2.9Gi       1.3Gi       203Mi        47Mi       1.4Gi       1.4Gi
Swap:             0B          0B          0B

KERNEL: 6.3.8-arch1-1 (x86_64)
SHELL: /bin/bash
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo

==== Lemmy Easy Deploy Information ====
Version: 1.1.0
Integrity:
    c8d59317549f098f04a6d333b4cf7fd0c222ad89004f37f18bde5800d469d964  ./deploy.sh
    1e9b0c0988998dcc33cb0fbfdb0e1679229424e724f898b797380adc7d102446  ./templates/Caddy-Dockerfile.template
    c1202e70662dd2228da36a35a0f38ec8fc81bec8964d7315d02e8671a58dd7d7  ./templates/Caddyfile.template
    7754ef7e8aa7e925becfcbbda0f873387533397a0756405741f4f4b9eb7f7253  ./templates/cloudflare.snip
    1df196524e8d55a4be93b5bf401669d61b372c4f6f7670da83ab1947631fd0ed  ./templates/compose-email.snip
    839ce56196227e2bac2291ee045ef95bc6af9c9706396352f39cb0812754c5c1  ./templates/compose-email-volumes.snip
    257270c0a1d59b7b2033b516c21dda10367009d5c66f371b94da39d42c692a1f  ./templates/docker-compose.yml.template
    308b8a122ee03cb9f5279fc2ad79663b0bffb2ed2a4042b96f678715cc997914  ./templates/lemmy-email.snip
    8f25408461972b9b66ee3c4d3f6430e2e1eaa950394d2d8b7e3d1287fe0d8f07  ./templates/lemmy.hjson.template

==== Settings ====
BUILD_FROM_SOURCE=true
CADDY_HTTP_PORT=80
CADDY_HTTPS_PORT=443
USE_EMAIL=false
CADDY_DISABLE_TLS=false
POSTGRES_POOL_SIZE=5
TLS_ENABLED=true

==== Generated Files ====
total 44K
drwxr-xr-x  2 0 0 4.0K Jun 22 01:07 caddy
-rw-r--r--  1 0 0   87 Jun 22 10:59 caddy.env
-rw-r--r--  1 0 0 2.1K Jun 22 10:59 docker-compose.yml
drwxr-xr-x 14 0 0 4.0K Jun 22 11:01 lemmy
-rw-r--r--  1 0 0   50 Jun 22 01:03 lemmy.env
-rw-r--r--  1 0 0  479 Jun 22 10:59 lemmy.hjson
drwxr-xr-x  7 0 0 4.0K Jun 22 11:01 lemmy-ui
-rw-r--r--  1 0 0   49 Jun 22 01:03 pictrs.env
-rw-r--r--  1 0 0   37 Jun 22 10:59 postfix.env
-rw-r--r--  1 0 0   51 Jun 22 01:03 postgres.env
-rw-r--r--  1 0 0    7 Jun 22 01:10 version
```

**Comment by ubergeek77** [comment]
Ah, this is because they moved the Dockerfile. Did you see this message when you tried to build?

```
ERROR: Unable to find Lemmy Dockerfile for building
    No such file: ./live/lemmy/docker/prod/Dockerfile

It is likely that Lemmy restructured their build files in a recent update.
If Lemmy Easy Deploy is already up to date, please report this so I can find the correct file path:
    https://github.com/ubergeek77/Lemmy-Easy-Deploy/issues
```

(This is why my issue template asks you for logs too, btw)

They keep moving this file every release, so I don't have a great way of dealing with it that won't break both release and RC versions.

For the time being, you can try changing this variable to be `docker/Dockerfile`:

https://github.com/ubergeek77/Lemmy-Easy-Deploy/blob/2b61859a2122cddcf0aaff140b665f0459b8b755/deploy.sh#L362

That gets a build going for me. Not sure if it will finish successfully though. But any build issues are in the Lemmy team's hands now, I only use their Dockerfile.

Let me know if that works!

**Comment by lordkitsuna** [comment]
Yeah sorry about that, I guess I'm just getting burned out from all the Federation issues. And even just deployment issues, without your script I wouldn't even have an instance. I'm not new to hosting or to docker I have 12 other services that I host regularly without issue but the instructions for lemmy are horribly broken, bothddocker and raw build lol.

I had not seen that message but turns out that's because I formatted my version tag incorrectly i was doing rc-6 instead of rc.6 for some reason and as far as I can tell only releases is checked if a version is not specified.

Thank you for the help, the build sadly failed with "failed to receive status: rpc error: code = Unavailable desc = error reading from server: EOF " although given the lower spec nature of this VPS that very well could have been the build running out of memory and killing itself. Guess I'll have to test this on my server at home but even if it did work there I'm not sure how I would then move it to the VPS

**Comment by ubergeek77** [comment]
All good!

And yes, I don't automatically search for RC versions at all. I don't want people accidentally installing an untested version that breaks their database. Lemmy does a database migration every release, and if things go wrong, it can easily result in the instance breaking with no option to downgrade. So because of that, I only look for "Release" versions, and leave the manual build tags up to whatever the user wants to use.

Not sure about that build error. It could be your VPS, or it could be that they simply haven't finished the Docker stuff yet. I imagine that would be tested pretty late into the RC. I'm testing this on the cheapest VPS my provider offers though, and the build is still running, so maybe yours did get killed after all?

Once they push the Docker images for 0.18 and formally release it, I'll make sure this project is updated to be as seamless as possible!

**Comment by lordkitsuna** [comment]
I actually managed to get it working. I decided to do a Hail Mary and just wipe all images all networks and all containers and start over. I was able to get it to deploy! Don't know what it got stuck on before but it is possible to deploy that particular RC tag of 18.6

but the site was half broken and logins were not working so i wiped everything and started from blank. now I'm getting database password failures for user lemmy. so perhaps they use a different login for the rc builds or something.

I am going to just give up and go back to release build but that information might be useful to someone else who wishes to try and dig a Little Deeper at it

**Comment by ubergeek77** [comment]
Thank you very much for testing! This will be very helpful things to know when I'm updating this project to support 0.18

**Comment by lordkitsuna** [comment]
Just as a quick little update to this. Seeing is how I had a malformed configuration I decided to wipe everything again and try again with this RC tag and it has worked. It is now online and running :) lemmy.kitsuna.net is on rc.6 thanks for all the help today lol

**Comment by ubergeek77** [comment]
You're welcome! Enjoy the RC! I think I'll put up with the websockets spam down here on 0.17.4 for just a little longer 😅
