### ISSUE TITLE
New version of lemmy

### ISSUE THREAD

**Issue by pallebone** [ubergeek77/Lemmy-Easy-Deploy#101]
0.19.7

**Comment by ubergeek77** [comment]
I am aware, thanks. There are no changes needed to the deployment files. Are you having any issues?

**Comment by ubergeek77** [comment]
Or do I lock the versions...? It's been a few months, let me take a look

**Comment by pallebone** [comment]
Interesting. No I havent changed anything or tried to upgrade anything right now. So just change the versions and see if it works?

**Comment by ubergeek77** [comment]
Yep that's right.

The deployment files haven't been changing very often. The only upstream differences since the last time I made an update 5 months ago were:

- Some nginx settings not relevant to this project since I use caddy
- Upstream officially changed to `pgautoupgrade`, which I already did for the 0.19.4 migration

You can see the upstream changes visually here:

https://github.com/LemmyNet/lemmy-ansible/compare/c872f2d1f39dd6db0da7f8a5edbbbe4199d70407...817a06e3517d6e3e0ac06118e6d4b4e530702861#diff-d3d33979648a9836685e314d1864481561d5130a294cce04be84b03c29abfb08

This project is designed to automatically pull the latest version of Lemmy, so I don't need to make manual changes unless the Lemmy maintainers make significant breaking changes to the deployment. So far it's been unchanged for 6+ months.

**Comment by pallebone** [comment]
Alright I will upgrade this week and see what happens

**Comment by ubergeek77** [comment]
Good luck on your update!

If it helps, my own instance upgraded from 0.19.5 to 0.19.7 using this script with no manual intervention required. I am the only user on my instance, but I haven't noticed any issues so far.

**Comment by pallebone** [comment]
Worked fine for me also.

**Comment by pallebone** [comment]
TNX
