### ISSUE TITLE
Various questions 

### ISSUE THREAD

**Issue by pallebone** [ubergeek77/Lemmy-Easy-Deploy#19]
Hi there,

Thank you for this script. I have success fully deployed via:

./deploy.sh -u 0.17.4 

Setup complete! Lemmy version 0.17.4 deployed!

I have various questions regarding this.

1) How can I backup this setup in case of server failure and then subsequently restore - eg: rebuild server etc. What can I do to ensure this is possible? Do I just backup the .live directory? To restore what is the process?

2) Do you have  a discord to communicate and test with? Would be helpful.

3) You need testers to test updating to 1.8.0 - please let me know what you would like me to do as I can test and help.

4) Official docs contain this information:
[Database tweaks](https://join-lemmy.org/docs/administration/install_docker.html#database-tweaks)
To optimize your database, add this file.
You can input your system specs, using this tool: https://pgtune.leopard.in.ua/
wget https://raw.githubusercontent.com/LemmyNet/lemmy-ansible/main/examples/customPostgresql.conf

How can I incorporate these tweaks into my setup?

5) I had to apply the fix from https://github.com/ubergeek77/Lemmy-Easy-Deploy/pull/18 in order to run the script.

Thank you for your time 

Kind regards
Peter

**Comment by ubergeek77** [comment]
1. I don't have a fully managed backup solution right now. I'm planning to make one when I have time, but I've been focusing on 0.18.x support and building multiarch images. Since this is based on Docker, backing up the `live` folder is ***not*** enough. You will have to back up your Docker volumes as well. For now, you can use various online resources that cover backing up Docker volumes so you can do it manually. You can read my comment here for some more detailed info:
https://github.com/ubergeek77/Lemmy-Easy-Deploy/issues/7#issuecomment-1599519411

2. No, I don't have the capacity or interest in managing a Discord community, sorry.

3. You can check out the pinned issue "Update plans for 0.18.x" to see what I've left to work on, and if you're comfortable helping me test, you can run a `git pull` on your install (stashing or checking out any changed files first), and then run `git checkout staging`. You can then use the staging version of 1.2.0. Thanks for helping me test!

4. I wasn't aware of this at all, actually. They don't document where that file goes, though. I'll consider it for a future update. For now, you can edit the files in `./live`, with `docker-compose.yml` in particular. You probably need to mount that over a config file in the postgres database. They don't document the path, so I don't have any specific details.

5. Yeah I was in a hurry before bed, whoops 😅

**Comment by pallebone** [comment]
Ok thank you,

Can you give me some tips on how I would setup email/ what to files to configure?

Also for upgrading what steps should I perform exactly and what do you expect will work/break?

Kind regards
Peter

**Comment by ubergeek77** [comment]
I have limited tips available for email. I provide an interface for the official Lemmy config file's SMTP settings, and the config.env.example file is pretty heavily commented.

I also have a setting that will start a postfix server along with the deployment, but after that, you're pretty much on your own. Sorry! Most people use this to run instances just for themselves, and I do not have any email systems set up right now, or any VPSes with port 25 allowed. The official Lemmy docs are sparse on email details, and I don't use email myself, so I have very basic support for it here.

After you've checked out the staging branch, in theory you should be able to just run `./deploy.sh`. If you're on 0.17.4, it *should* update you to 0.18.0, and if you're already on 0.18.0, it *should* do nothing. If you want to update to a release candidate version, you can try `./deploy.sh -l 0.18.0-rc.4 -f`. You might want to wait for an hour or two before doing that because I'm rebuilding that tag right now, but if the official Lemmy Docker images have that tag (which I think they do?), it should fall back to those and still work.

I tested this pretty well, and regardless your data is safe in your docker volumes as I don't touch those, but let me know if you run into issues.

**Comment by pallebone** [comment]
Ok I have email working, thank you.

I will look into backup and testing soon(later) today.

P

**Comment by ubergeek77** [comment]
Great to hear you got email working so quickly!

I'd love to hear any specific details about how you got it working, and especially if the email cryptography is working properly. I get a lot of requests about email, and while I don't use it myself, I am thinking about putting together a wiki page based on people's experiences.

**Comment by pallebone** [comment]
It is very simple I signed up for mailjet (200 free emails per day) and configured lemmy.hjson:

email: {
    smtp_server: "GETTHISPARTFROMPANEL.mailjet.com:587"
    smtp_login: "secret"
    smtp_password: "secret"
    smtp_from_address: "lemmy@myserv.one"
    tls_type: "tls"
  }

**Comment by pallebone** [comment]
My instance is https://lemmy.myserv.one/ which is why the email is in that format in case you were wondering.

**Comment by ubergeek77** [comment]
No funny business with the DNS records it looks like!

This means using email like this will be fully possible in Lemmy-Easy-Deploy 1.2.0. I've already added config options that set those values, so I'm happy to hear that's all you needed.

Thanks!

**Comment by pallebone** [comment]
Yes was super easy.

**Comment by pallebone** [comment]
Sorry I did add relevant DNS records like spf and dkim etc

**Comment by pallebone** [comment]
Sorry also can i upgrade direct to ./deploy.sh -l 0.18.0-rc.4 -f or must I go via 1.8.0?

**Comment by pallebone** [comment]
Ok I started by git checkout staging but got this:

**Comment by ubergeek77** [comment]
So, in 1.2.0, I have added some new config variables and removed some old ones. I put this warning here to prevent people from having unexpected behavior if they were using one of those.

I recommend:

- Copy your existing config.env: `cp ./config.env ./config.bak`
- Overwrite the old config with the new template: `cp ./config.env.example ./config.env`
- Refer to the old `config.bak` you made and move over any settings as needed

The new config format also provides settings for SMTP. You can now put those settings in `config.env` rather than edit `lemmy.hjson` manually (and `lemmy.hjson` will get overwritten, by the way).

**Comment by pallebone** [comment]
I did what you suggested but I get an unauthorised error?

```
Would you like to deploy this update? [Y/n] y     
Finding the best available Backend image, please wait...
! No reported architecture for ghcr.io/ubergeek77/lemmy:0.18.0; assuming linux/amd64
--> Using Backend Image: ghcr.io/ubergeek77/lemmy:0.18.0

Finding the best available Frontend image, please wait...
! No reported architecture for ghcr.io/ubergeek77/lemmy-ui:0.18.0; assuming linux/amd64
--> Using Frontend Image: ghcr.io/ubergeek77/lemmy-ui:0.18.0

Pulling pictrs   ... done
Pulling postgres ... done
Pulling lemmy    ... error
Pulling lemmy-ui ... error
Pulling proxy    ... done

ERROR: for lemmy  Head "https://ghcr.io/v2/ubergeek77/lemmy/manifests/0.18.0": unauthorized

ERROR: for lemmy-ui  Head "https://ghcr.io/v2/ubergeek77/lemmy-ui/manifests/0.18.0": unauthorized
ERROR: Head "https://ghcr.io/v2/ubergeek77/lemmy/manifests/0.18.0": unauthorized
Head "https://ghcr.io/v2/ubergeek77/lemmy-ui/manifests/0.18.0": unauthorized
```

**Comment by ubergeek77** [comment]
Hmmm, I need to update my image checking code. It should have fallen back to the Dessalines images here. I don't have 0.18.0 in my repo, I only have 0.18.1-rc.4

**Comment by ubergeek77** [comment]
This is so weird, I don't get this bug at all. I noticed your Docker version is 4 versions behind, and your Compose version is 1 version behind, I wonder if the output of `docker manifest` has changed.

**Comment by ubergeek77** [comment]
@pallebone 

Can you post the output of either/both of these commands on your system? You'd be doing me a huge favor in making this more reliable:

```
docker buildx imagetools inspect ghcr.io/ubergeek77/lemmy:0.18.0

docker manifest inspect ghcr.io/ubergeek77/lemmy:0.18.0
```

I think the pattern of that output is just different on the version of Docker you're using. This is why I direct people to install the official version of Docker rather than the Ubuntu/distro versions, but I'd like to be able to support both!

**Comment by ubergeek77** [comment]
Actually, I was able to reproduce this, and I think fix it:

https://github.com/ubergeek77/Lemmy-Easy-Deploy/commit/7ec20da82b6f5f8c6463257a651356b2535bd7e8

Please run `git pull` to pull this update, then try again. Your deployment should fall back to the official 0.18.0 images, and the issue you experienced should not happen anymore.

**Comment by pallebone** [comment]
No problem, I tried again and got this:

```
Would you like to deploy this update? [Y/n] y
Finding the best available Backend image, please wait...
! ghcr.io/ubergeek77/lemmy:0.18.0 is not available for amd64
! Checking backup image at dessalines/lemmy:0.18.0...
ERROR: A Lemmy Backend image for your architecture is not available (amd64)
If you are confident that this image exists for 'amd64', please report this as an issue: 
    https://github.com/ubergeek77/Lemmy-Easy-Deploy/issue
root@lemmy:/lemmy/Lemmy-Easy-Deploy# 
```

**Comment by ubergeek77** [comment]
@pallebone 

This is because, apparently, older Docker versions like yours do not support remote images with attestation manifests. It treats them as if they do not exist.

I ***do*** have a warning about unsupported Docker versions in the README:

https://github.com/ubergeek77/Lemmy-Easy-Deploy#prerequisites--quick-start

However, in 1.2.2, I have added a compatibility fix for this specific issue. In the future, if you run into issues, I recommend installing the latest version of Docker.  I've added a warning about older Docker versions to 1.2.2, with a link to instructions on installing it.

Please try 1.2.2 and let me know if it works!

```
./deploy.sh --update
```

**Comment by pallebone** [comment]
Hello,

Thank you I agree it worked. I have some issues i would like to raise next week as well as work with you upgrading to 0.18.1 if possible but I will open a new ticket.

For now it all seems to be working (lemmy.myserv.one) and indeed it is possible to update. The docker version on Debian 12 was not updated and I just used the workaround script 1.2.2.

Kind regards
Peter

**Comment by ubergeek77** [comment]
Feel free to open an issue with any issues you encounter!

As for 0.18.1, everything is ready to go. Once the Lemmy team releases it, you can just run ./deploy.sh and it will go through the update process for you. I shouldn't need to update Lemmy-Easy-Deploy for 0.18.1 unless they make a last minute major change!

**Comment by pallebone** [comment]
Thank you :)
