### ISSUE TITLE
admin username ignored

### ISSUE THREAD

**Issue by danmed** [ubergeek77/Lemmy-Easy-Deploy#22]
# The admin username for first time setup
SETUP_ADMIN_USER="thisisme"

The above portion of config.env appears to be being ignored..

**Comment by danmed** [comment]
I'm an idiot.. i was re-deploying but didn't delete the live folder first..

**Comment by ubergeek77** [comment]
@danmed No worries! But remember, your data is stored in docker volumes, not the live folder. The live folder just has deployment files and secrets.

List out your docker volumes with this:

```
docker volume ls
```

If you want to clear the postgres database, you should delete the one with `postgres_data` in the name. Otherwise, anything with "setup" in the name won't apply, because the deployment will just grab your old volume!

**Comment by danmed** [comment]
Yep,  I had gotten rid of all images, volumes and containers.. but when
running deploy.sh, if the live folder is already populated then it doesn't
output the default username and password on completion and will also ignore
the username set in config.env.

i had to rm -rf it to get things to play ball as a new install.
