### ISSUE TITLE
Question: Does this provide a Lemmy-standard installation? 

### ISSUE THREAD

**Issue by calr0x** [ubergeek77/Lemmy-Easy-Deploy#27]
First off huge thanks for this project!

Does this provide an installation compatible with the standard Lemmy docker installation aside from the docker image name?

Might start with your project to install but if you decide to stop development or slow updates I can follow the update procedure from the standard Lemmy instructions.

Thanks again!

**Comment by ubergeek77** [comment]
> Does this provide an installation compatible with the standard Lemmy docker installation aside from the docker image name?

Pretty much! I wouldn't exactly call upstream's Docker deployment a "standard," since they change it pretty frequently, but I do try my best to keep my deployment up to date with theirs.

The reason I use my images instead of theirs is because they have broken ARM support in `0.17.4`, and don't seem to be in a hurry to fix it. I have a good number of users on ARM, so by providing multiarch images and making them the default in my script, everyone can use Lemmy easily.

There is no real difference between my images and theirs other than this. Mine are based on Debian, while theirs are based on Alpine, but a while back the official images were based on Debian too. [The Dockerfiles I use to build those images](https://github.com/ubergeek77/lemmy-docker-multiarch/actions) are nearly identical to the official Dockerfiles, just with changes to make them platform-independent and allow them to build on any architecture.

In fact, they are so similar, that in my script, if I haven't yet built an image for the tag you're trying to deploy, it will fall back to the official image name. They are completely interchangeable.

> Might start with your project to install but if you decide to stop development or slow updates I can follow the update procedure from the standard Lemmy instructions.

If I do ever decide to stop development, you won't be "locked in" to my script. My script automates the initial creation of passwords, and also does some autodetection to make sure the deployment files work best for your system, but other than that, the `./live` folder contains a fully-manageable Docker Compose deployment you can modify and redeploy as you usually would. The only real difference of note is I use a stack name of `lemmy-easy-deploy`, but you can just use the `-p` CLI argument to specify that.

I hope that clarifies things for you!

**Comment by calr0x** [comment]
It does! I really appreciate your time in answering my question, the help
you provide getting an instance rolled out, and the greater contribution
you are making to help all of us make this work!

I'm going to try to roll this out in the next day or two and I will give
you some feedback!

**Comment by ubergeek77** [comment]
You're welcome! Happy to help!
