### ISSUE TITLE
Prometheus Support?

### ISSUE THREAD

**Issue by Frorayz** [ubergeek77/Lemmy-Easy-Deploy#34]
**Did you check the [FAQ & Troubleshooting section](https://github.com/ubergeek77/Lemmy-Easy-Deploy/blob/main/TROUBLESHOOTING.md) for answers to common questions and issues?**
> Yes

**Describe the issue**
Adding Prometheus support? Since they just added it to the configs. https://github.com/LemmyNet/lemmy/commit/1e99e8b9dc48b23fca3b1801c66f30cf17766825

I am not sure if this suppose to be done manually? By manually entering docker

**Diagnostic Information**

```
==== Docker Information ====
Detected runtime: docker (Docker version 24.0.3, build 3713ee1)
Detected compose: docker compose (Docker Compose version v2.19.1)
   Runtime state: OK

==== System Information ====
      OS: Linux
  KERNEL: 5.15.0-76-generic (x86_64)
HOSTNAME: OK
   SHELL: bash
  MEMORY:
               total        used        free      shared  buff/cache   available
Mem:           7.8Gi       550Mi       2.8Gi       144Mi       4.4Gi       6.8Gi
Swap:             0B          0B          0B

DISTRO:
----------------------------
PRETTY_NAME="Ubuntu 22.04.2 LTS"
NAME="Ubuntu"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
----------------------------

==== Lemmy-Easy-Deploy Information ====
Version: 1.2.6

IMAGE                                      CREATED       STATUS
caddy:latest                               2 hours ago   Up 2 hours
ghcr.io/ubergeek77/lemmy-ui:0.18.1-rc.11   2 hours ago   Up 2 hours
ghcr.io/ubergeek77/lemmy:0.18.1-rc.10      2 hours ago   Up 2 hours
postgres:15-alpine                         2 hours ago   Up 2 hours
asonix/pictrs:0.4.0-beta.19                2 hours ago   Up 2 hours

Integrity:
    789dff42875ab8c43692ddeef7600ef3b3c0a5abf24d84efe6cdae49a46e7ce7  ./deploy.sh
    1e9b0c0988998dcc33cb0fbfdb0e1679229424e724f898b797380adc7d102446  ./templates/Caddy-Dockerfile.template
    c1202e70662dd2228da36a35a0f38ec8fc81bec8964d7315d02e8671a58dd7d7  ./templates/Caddyfile.template
    2537678c7971df36c1ed95f4228d3cfcb15bb4a28a60d939eaf8dd75b5d64a36  ./templates/cloudflare.snip
    c494a610bcb4cd1cfc0a4fe4fb0f6d437b2a84a0ad1625daee240e6dd6f1c910  ./templates/compose-email-volumes.snip
    c9cb4c5fee12930e17798a02ae1bd12e2dc69e149a394c24511bc9d4e6b776d4  ./templates/compose-email.snip
    d9928baea61975bd432e1a4a7439c04468547c9b42e2bb483c6f18d9438665eb  ./templates/docker-compose.yml.template
    a74770730fd0e809d44e5247e1300be04c2b664be13d06bfec00296e3e63861b  ./templates/lemmy-email.snip
    c834cdce9eaf77f38155b404724fdfe66845575386ee516987452aa715642a6f  ./templates/lemmy.hjson.template

Custom Files: 
*** No custom files ***

==== Settings ====
        CLOUDFLARE: No
 CADDY_DISABLE_TLS: false
   CADDY_HTTP_PORT: 80
  CADDY_HTTPS_PORT: 443
 LEMMY_TLS_ENABLED: true
      ENABLE_EMAIL: true
         SMTP_PORT: 587
    ENABLE_POSTFIX: false
POSTGRES_POOL_SIZE: 5

==== Generated Files ====
Deploy Version: 0.18.1-rc.10;0.18.1-rc.11

total 36K
drwxr-xr-x 2 0 0 4.0K Jul  3 02:58 caddy
-rw-r--r-- 1 0 0   33 Jul  7 00:41 caddy.env
-rw-r--r-- 1 0 0 1.7K Jul  7 00:41 docker-compose.yml
-rw-r--r-- 1 0 0   50 Jul  3 02:58 lemmy.env
-rw-r--r-- 1 0 0  730 Jul  7 00:41 lemmy.hjson
-rw-r--r-- 1 0 0   49 Jul  3 02:58 pictrs.env
-rw-r--r-- 1 0 0   37 Jul  7 00:41 postfix.env
-rw-r--r-- 1 0 0   51 Jul  3 02:58 postgres.env
-rw-r--r-- 1 0 0   26 Jul  7 00:41 version
```

**Comment by ubergeek77** [comment]
Hello!

Unfortunately, the new Prometheus metrics are not something that I currently have the capacity to provide support for. Prometheus is not very welcoming to non-tech-savvy users, and if you want to use it, chances are you will understand what changes you need to make in order to use it.

Just a moment ago, I did release Lemmy-Easy-Deploy v1.2.7, which allows you to fully customize your deployment however you like, although I cannot provide support for people using this feature. "Hack away at your own risk," so to speak:

https://github.com/ubergeek77/Lemmy-Easy-Deploy/releases/tag/1.2.7

With this, you will be able to edit the deployment template however you like, although you are on your own. You may want to refer to the official `docker-compose.yml`. You will probably want to add this port manually:

https://github.com/LemmyNet/lemmy/blob/b3dfc3721f8879525f64c6a1bdf2d64c34b20c9f/docker/docker-compose.yml#L42-L45

Right now, the images you are using (my images, `ghcr.io/ubergeek77/lemmy/lemmy-ui`) were not built with Prometheus metrics enabled in `CARGO_BUILD_FEATURES`. So if you are trying to use Prometheus, the metrics won't be available.

Once `0.18.1` is released, I will ensure my images are built with whatever features the official images have enabled, but you will still need to manage your deployment manually to add Prometheus support.

Good luck!

**Comment by ubergeek77** [comment]
I will keep this open to track this as a feature, if it really is as simple as adding a port and an extra config block, I can support it in Lemmy-Easy-Deploy, but only if the official images also build with this feature enabled. Currently, the official Dockerfile does not enable this feature.

I will keep an eye on the `0.18.1` release and update this issue accordingly. In the meantime, you can use the advanced configuration I posted above to manually use your own image and add the necessary config blocks.

**Comment by ubergeek77** [comment]
It looks like the official 0.18.1 images still do not compile with Prometheus support enabled. I've asked them on their GitHub if this was an oversight or an intentional choice.

**Comment by ubergeek77** [comment]
Ok, unfortunately, this is not an "upstream feature" for the time being:

https://www.github.com/LemmyNet/lemmy/pull/3456#issuecomment-1626000225

Since the Prometheus endpoint isn't compiled into the official images, sadly it's not feasible for me to directly support it in Lemmy-Easy-Deploy. I would have to add this feature to my unofficial images so that this script can use it. But if it's not stable enough for the official images, I don't feel comfortable building it into mine.

However, to accomodate this, I will add a feature to Lemmy-Easy-Deploy that allows you to override what images are used. You can of course modify the script yourself to do this now, but that will make it a little easier to manage long term.

That, along with the advanced customization features I've recently added, should allow you to build Lemmy yourself and get Prometheus working.

I'll close this now, but I will ping you when I have done that and give some brief (untested) guidance about how you can go about this.
