### ISSUE TITLE
Lemmy fails to build on ARM-based systems

### ISSUE THREAD

**Issue by Christoph-Wagner** [ubergeek77/Lemmy-Easy-Deploy#4]
```
Distributor ID: Debian
Description:    Debian GNU/Linux 12 (bookworm)
Release:        12
Codename:       bookworm
```

```
Architecture:            aarch64
  CPU op-mode(s):        32-bit, 64-bit
  Byte Order:            Little Endian
CPU(s):                  2
  On-line CPU(s) list:   0,1
```

```
[+] Pulling 5/5
 ✔ lemmy Skipped - No image to be pulled                                                                           0.0s
 ✔ lemmy-ui Skipped - No image to be pulled                                                                        0.0s
 ✔ pictrs Pulled                                                                                                   0.9s
 ✔ postgres Pulled                                                                                                 0.9s
 ✔ proxy Pulled                                                                                                    0.9s
[+] Building 8.5s (11/14)
 => [lemmy internal] load .dockerignore                                                                            0.0s
 => => transferring context: 159B                                                                                  0.0s
 => [lemmy internal] load build definition from Dockerfile                                                         0.0s
 => => transferring dockerfile: 613B                                                                               0.0s
 => [lemmy internal] load metadata for docker.io/library/alpine:3                                                  0.3s
 => [lemmy internal] load metadata for docker.io/clux/muslrust:1.67.0                                              0.3s
 => [lemmy builder 1/6] FROM docker.io/clux/muslrust:1.67.0@sha256:c92ad5296e87681efa161fdb7421bb136ba5df399441a4  0.0s
 => CACHED [lemmy lemmy 1/3] FROM docker.io/library/alpine:3@sha256:82d1e9d7ed48a7523bdebc18cf6290bdb97b82302a8a9  0.0s
 => [lemmy internal] load build context                                                                            0.2s
 => => transferring context: 1.92MB                                                                                0.2s
 => CANCELED [lemmy lemmy 2/3] RUN apk update && apk add libpq                                                     0.7s
 => CACHED [lemmy builder 2/6] WORKDIR /app                                                                        0.0s
 => [lemmy builder 3/6] COPY ./ ./                                                                                 0.2s
 => ERROR [lemmy builder 4/6] RUN echo "pub const VERSION: &str = "$(git describe --tag)";" > "crates/utils/src/v  0.2s
```

Repeatedly fails at that point when running deploy.sh

**Comment by ubergeek77** [comment]
Unfortunately, I can't fix this at the moment. When searching why this might happen to you, I found out that Lemmy is having problems with ARM builds as well. They are directing people to use the "from scratch" build rather than the Docker build. I guess this explains why 0.17.4 never got an ARM image on Docker Hub...

Since Lemmy Easy Deploy relies on the build files Lemmy provides, any build issues they have will affect my project as well. Once they sort out their ARM build issues in a future update, Lemmy Easy Deploy should work again.

As a temporary hacky workaround for the time being, you can try removing this `if` block here:

https://github.com/ubergeek77/Lemmy-Easy-Deploy/blob/3102cc7eea524cb527a6adeef98ed4d173d376a3/deploy.sh#L238,L248

And then run `./deploy.sh -u 0.17.3-linux-arm64 -f` to pull the last available ARM image they had.

I hope that works for you, but to be honest, it looks like Lemmy does not have great support for ARM based systems. x86_64 seems to be the preferred architecture.

**Comment by ubergeek77** [comment]
Good news! I've got a better fix for you.

Lemmy's ARM images are still a mess, but I didn't realize they had a separate ARM Dockerfile for 0.17.4. I've pushed an update to Lemmy Easy Deploy that will detect if it needs to be used, and switch to it if necessary. It looks like it compiles ok.

It looks like this separate .arm file is being removed in a future update, so 0.18.x might be a little rocky for ARM users unless they find a stable solution, but for now, this should get you going :)

If you followed my workaround before, and managed to get Lemmy working, you can run these commands to update to 0.17.4:

```
git checkout deploy.sh
git pull
./deploy.sh -u 0.17.4 -f
```

Since there still aren't prebuilt ARM images for 0.17.4, this will need to compile Lemmy from source, which will take about 30 minutes (depending on your system resources), but if you have an existing instance running already, it won't be taken down until the compile is complete, so you can continue to use it while you wait.

**Comment by Christoph-Wagner** [comment]
This is great, thank you. I’ll have a look at this later. I guess I’ll also read some on the lemmy repo & chat about the future for ARM before I make this single-user instance my primary one :D
