### ISSUE TITLE
Security Concerns

### ISSUE THREAD

**Issue by izz-j** [ubergeek77/Lemmy-Easy-Deploy#41]
As this project is meant for beginners to host their own instance. Many are opening port 80 and 443 possibly on their home network. I wanted to know what security strategies you'd recommend? Sorry if this is out of scope of the project. But since Lemmy-Easy-Deploy will be used by many beginners, I think it is a good question. Thank you.

**Comment by ubergeek77** [comment]
Hello!

I actually **do not recommend self hosting on a home network.** I can't stop people from doing this, but if people are port forwarding in order to use this at home, they are doing so at their own risk.

My intention for this script has always been that people self host using a public VPS provider, like Vultr, Linode, or DigitalOcean. Lemmy is a 24/7 ActivityPub server, and home networks are famously unreliable. Many people's home internet connections go down frequently, and I don't think most consumer-grade network equipment can handle the complete onslaught of data that your network will receive 24/7 due to federation. It just isn't a good idea to host at home.

If you must host at home, I would recommend at least using the Cloudflare proxy, and only allowing Cloudflare's IP ranges through your firewall, but I still do not recommend that users host at home even with Cloudflare.

Please always host on a cloud server!
