### ISSUE TITLE
Upgrade to Git Commits?

### ISSUE THREAD

**Issue by Frorayz** [ubergeek77/Lemmy-Easy-Deploy#43]
**Did you check the [FAQ & Troubleshooting section](https://github.com/ubergeek77/Lemmy-Easy-Deploy/blob/main/TROUBLESHOOTING.md) for answers to common questions and issues?**
> Yes

**Describe the issue**
Is there a way to upgrade to Git commits instead of tags?

**Diagnostic Information**
N/A

**Comment by ubergeek77** [comment]
Yes, you can do `-l git:<hash>` or `-w git:hash`

However, I tried doing a git build just today and the build failed, and I don't really have the capacity to fix their builds for them [a second time :p](https://github.com/ubergeek77/lemmy-docker-multiarch) 

You can use those CLI args to build against a git commit, and if it fails/you need to make changes, you can use the `-r` flag to rebuild without clearing the git tree.

Do note that this is:

- Not going to be stable, you'll be lucky if it builds at all
- Not tested a lot in LED by me, and barely supported, because...
- Builds can take upwards of 30-40 minutes depending on your machine, Rust builds very slowly.

However, I should mention that I am building Docker images for every commit they tag, meaning I have 0.18.2-rc.2 images ready to pull. I think that has every security fix they've pushed recently, at least the most critical ones.

If your build fails, I won't be able to really help, but you can keep trying different things with the `-r` flag if you need to fix it. You can also take a look at my Dockerfiles in the repo I linked if their Dockerfiles are problematic for you.

**Comment by Frorayz** [comment]
Thank you for the quick and detailed reply. So if I were to build using commits and it failed you saying -R would force it to build again without clean the working directory? Right?

**Comment by ubergeek77** [comment]
Yep. I've basically got it set up like this:

- It will clone and checkout if it doesn't exist at all, at the hash/tag you specified
- If `-r`/`--rebuild` is specified, `REBUILD_SOURCE` gets set to `1` which will completely ignore the `git reset/checkout` commands:

https://github.com/ubergeek77/Lemmy-Easy-Deploy/blob/61827fdb13dc171316967c330794fe29ad48983c/deploy.sh#L1409-L1446

**Comment by ubergeek77** [comment]
If you have any feedback about this, or any unexpected not-upstream-Lemmy issues, feel free to let me know. This build from source code is pretty old at this point, it was only there for myself, but ended up being replaced by my multiarch images which I use for myself now.

**Comment by Frorayz** [comment]
Got it thank you again for this detailed answer. I will just stick with the tagged versions for now. Closing this.

**Comment by ubergeek77** [comment]
Sounds good! You're probably asking about this due to all the recent security news. So, if you're keeping an eye on these security fixes, I am building all RC versions pretty much as soon as they are tagged (my server checks for missing tags every 20 minutes). If you see a new Lemmy tag, chances are I've already got an image for it before even the official images are ready, in which case you can do, for example:

```
./deploy.sh -l 0.18.2-rc.2 -f
```

(`-l` on its own implies `-w` of the same tag for convenience, you can also set `-w` to `0.18.0` or something if you want to stay there)

You can always see what the newest tags I have for each image by going to each package individually:

https://github.com/ubergeek77/lemmy-docker-multiarch/pkgs/container/lemmy
https://github.com/ubergeek77/lemmy-docker-multiarch/pkgs/container/lemmy-ui

**Comment by Frorayz** [comment]
Yes, I have noticed you are really fast. Which is great and I am so appreciative of you! I just saw more fixes with CORS in commits and they haven't tagged a new version yet. That's why I wanted to be ahead of security issues and use the commits instead. But again thank you so much!!
