### ISSUE TITLE
0.18.3-rc.2

### ISSUE THREAD

**Issue by airjer** [ubergeek77/Lemmy-Easy-Deploy#51]
Using this to upgrade to 0.18.3-rc.2 creates nothing but an error page causing you to revert back to the latest stable release. After this is done, when you create a post it's just an endless loop visibly, but the post gets created.

**Comment by ubergeek77** [comment]
Unfortunately, I cannot provide assistance with unofficial release candidate versions. It's possible they may break, and while reports of breakage are helpful for me to prepare for new versions, I can't do much other than ensure the latest stable version works once it is released officially.

However, it would help if you had not [skipped the issue template](https://github.com/ubergeek77/Lemmy-Easy-Deploy/issues/new?assignees=&labels=&projects=&template=issue_report.md&title=), as this provides me with helpful info to understand what's going on :)

**Comment by airjer** [comment]
Yeah I understand, just thought I'd report. Sorry the issue template wasn't even there for me when I created the post this time for some reason. Will it help at all with me being back on the stable release? Or is there anywhere else you'd like me to copy from that would help you?

**Comment by airjer** [comment]
Actually, it seems that quite possibly this has completely ruined my instance again keeping posting from syncing elsewhere. 🤦‍♂️

**Comment by ubergeek77** [comment]
Ah, that is unfortunate. That is why Lemmy Easy Deploy has a very hard-to-miss warning about upgrades, as the Lemmy team has a habit of changing the schema pretty much every release. It's possible something got changed, breaking your instance. In that warning, I recommend taking a backup, which is especially advised for untested RC versions.

As for 0.18.3-rc.2, unfortunately I was not able to reproduce any deployment issues, everything is perfectly fine:

![image](https://github.com/ubergeek77/Lemmy-Easy-Deploy/assets/3455585/95d63f3c-4e43-45f5-90c9-466fb2ff4a3e)

With RC's, this could be caused by really anything, and unfortunately I don't have much capacity to support Lemmy issues that aren't related to a misconfiguration in the deployment files. Everything looks good to go on my end, and I am also monitoring their reference deployment files. No significant changes were made.

If you upgrade back to 0.18.3-rc.2 and then post some logs, I may be able to point you in the right direction, but ultimately this may need to be filed as an issue on one of the Lemmy issue trackers, depending on if this is a UI ir Backend issue (I should be able to help you deduce at least that much)

**Comment by ubergeek77** [comment]
I should mention, during the database migration, the UI **_will_** seem like it's throwing errors, but in reality, it's not ready to serve content yet, appearing as an error. Is it possible you shut it down too fast before the migration was complete?

If that's the case, maybe you could try re-upgrading to the RC version and waiting a little while.

**Comment by airjer** [comment]
Well good news, I just noticed rc3 released so I gave that a go and everything seems to be working fine! Wish I had more input for you as to what happened, but maybe your last explanation possibly is what happened? I'm not entirely sure.
