### ISSUE TITLE
0.8.3 seems to break email

### ISSUE THREAD

**Issue by pallebone** [ubergeek77/Lemmy-Easy-Deploy#53]
email: {
    smtp_server: "in-v3.mailjet.com:587"
    smtp_login: "redacted"
    smtp_password: "redacted"
    smtp_from_address: "lemmy@myserv.one"
    tls_type: "starttls"

I logged a bug here:

https://github.com/LemmyNet/lemmy/issues/3757

Unclear why email did work but no longer functions at all :(

Any input appreciated in advance. Assume a lemmy bug but not actually sure.

**Comment by ubergeek77** [comment]
This one is out of my control I'm afraid. Based on your bug report there, it doesn't seem like there are any issues with the configuration.

You may get more traction if you put "email" in your issue title over there. The title currently is kinda ambiguous.

Also, anecdotally, I've noticed that my own emails on <=0.18.2 work fine for comment replies, but don't work for private messages from other instances. If I message myself, it's fine, but if another instance's user messages me - no email.

Given that, I would not be surprised if there is some email bug in Lemmy somewhere, since email was already shaky before 0.18.3.

**Comment by pallebone** [comment]
Its possible, but wanted to log the bug here in case you knew anything being a little more familiar with the setup, and presumably being able to test if you have a similar issue if you run an upgrade test at some point.

**Comment by pallebone** [comment]
I believe the issue is mitigated to the admin user only which (no surprise) was the email I decided to test with

**Comment by pallebone** [comment]
Closing as bug is 100% upstream.

**Comment by airjer** [comment]
same issues on mine after the upgrade, no emails work and no verification emails are being sent it seems
