### ISSUE TITLE
Add cron job to the README/Updating section

### ISSUE THREAD

**Issue by danielkrajnik** [ubergeek77/Lemmy-Easy-Deploy#79]
**Did you check the [FAQ & Troubleshooting section](https://github.com/ubergeek77/Lemmy-Easy-Deploy/blob/main/TROUBLESHOOTING.md) for answers to common questions and issues?**
> Yes

**Describe the issue**
> What happened? Post any relevant log snippets.

Thank you for creating this repo. I've gone through both ansible and docker from lemmy's official documentation and without your scripts I would have given up on lemmy!

It may be obvious, but it may be helpful to some users if README also included a cron job to keep the deployment up to date? Even something simple like:

`crontab -e`

```sh
# every day at 4:21am
21 4 * * * cd ~/Lemmy-Easy-Deploy && git pull origin main && git checkout $(git describe --tags `git rev-list --tags --max-count=1`) && ./deploy.sh
```

**Comment by ubergeek77** [comment]
Thank you for your suggestion! However due to Lemmy's history of having a few mishaps during previous version bumps, and because I may ask the user questions in this script, I'm not comfortable recommending completely hands-off upgrades with no user confirmation.

However, you're welcome to continue doing this for your server, and I'll try to keep this in mind when working on the CLI!
