### ISSUE TITLE
Migrate from Ansible to Lemmy Easy Deploy

### ISSUE THREAD

**Issue by slrgt** [ubergeek77/Lemmy-Easy-Deploy#80]
**Did you check the [FAQ & Troubleshooting section](https://github.com/ubergeek77/Lemmy-Easy-Deploy/blob/main/TROUBLESHOOTING.md) for answers to common questions and issues?**
> Yes

Could a way to migrate from an ansible install to a lemmy-easy-deploy install be made? It would be extremely useful

**Comment by ubergeek77** [comment]
A while back, I created a helper script to migrate some data into Lemmy Easy Deploy, but keep in mind:

- I am not actively developed it
- It's not exactly what I would call user friendly

However, you are welcome to try it:

https://github.com/ubergeek77/Lemmy-Easy-Deploy/blob/staging/migrate.sh

You would have to know where in Ansible your data is stored in order to use this, but because I've never used the Ansible deployment, I don't have specific instructions.

However please keep in mind, my project is what I would call on "Maintenance Mode." Unless someone submits a PR, it won't support some more advanced features like pictrs image scanning.
