### ISSUE TITLE
"Unable to determine Frontend upgrade path" - version number parsing error

### ISSUE THREAD

**Issue by oz42** [ubergeek77/Lemmy-Easy-Deploy#81]
**Did you check the [FAQ & Troubleshooting section](https://github.com/ubergeek77/Lemmy-Easy-Deploy/blob/main/TROUBLESHOOTING.md) for answers to common questions and issues?**
> Yes

**Describe the issue**
> What happened? Post any relevant log snippets.

Ran deploy.sh and got this confusing message:

 Current Backend Version: 0.18.5
  Latest Backend Version: 0.18.5

 Current Frontend Version: 0.18.5
  Latest Frontend Version: 0.19.0-alpha.2

-----------------------------------------------------------------------------------------------------------
ERROR: Unable to determine Frontend upgrade path. One of the below versions is not in 0.0.0 format:
   Installed Frontend: 0.18.5
      Target Frontend: 0.19.0-alpha.2

Are you trying to install an "rc" version manually? Combine the -w flag with -f to skip the version check:
        ./deploy.sh -w <some-tag> -f

**Comment by ubergeek77** [comment]
This is because the Lemmy developers broke their versioning scheme and started tagging "alpha" releases. They only used to use "rc" or "beta" tags, so this is not a case I was expecting.

For now, you can use the command line arguments to force install alpha-2, or wait for me to fix it when I'm done visiting family this week 👍
